<?php $__env->startSection('title'); ?>
ESS - DTR
<?php $__env->stopSection(); ?>

<?php $__env->startSection('contents'); ?>
<h4>Daily Time Record</h4>
<nav>
	 <ol class="breadcrumb">
		  <li class="breadcrumb-item"><a href="<?php echo e(route('dashboard')); ?>">Dashboard</a></li>
		  <li class="breadcrumb-item">Daily Time Record</li>
	 </ol>
</nav>
<div class="mobile_view container-fluid table-responsive">
	<div class="form-group  mt-5">
		<h5>Displaying logs this week</h5>
	</div>
	<div style='overflow-x:hidden; overflow-y: auto; max-height: 70vh;'>
	    <table class="table table-bordered w-100">
		<thead class='table-header'>
			<tr>
				<th>Date</th>
				<th>Clock in</th>
				<th>Clock out</th>
			</tr>
		</thead>
		<tbody id="tbod">
			
		</tbody>
	</table>
	</div>
</div>

<div class="card nouhead" style="display:none;">
	<div class="card-body">
		<center>
			<h4>Please set your unit head.</h4>
			<a href="<?php echo e(route('jump_employeeabouts')); ?>">Set in My Profile</a>
		</center>
	</div>
</div>


<div class="row hasuhead" style="display: none;">
	 <div class="col-sm-7">
		  <!-- <div class="loading_indicator"></div> -->
		  <div class="form-group">
				<div class="card rounded">
					<div class="card-header mb-0">
						  <button class="btn btn-success float-right rounded" data-toggle="modal" data-target="#dtrsetupgeneration" onclick="SetupPasGeneration()"><i class="fas fa-print"></i> Print DTR</button>
					  <h5 class="card-title"><strong id="dd_from">April 11</strong> to <strong id="dd_to">July 19</strong></h5>
					</div>
					<div class="card-body p-0" style='background-color: #F2F2F2;'>
					    	<div style='overflow-x:hidden; overflow-y: auto; max-height: 70vh;'>
						 <table class="table table-hover m-0" id="dtr_attendalbetable">
								<thead class='table-header'>
									 <tr>
										  <th>Date</th>
										  <th class="text-center">AM In</th>
										  <th class="text-center">AM Out</th>
										  <th class="text-center">PM In</th>
										  <th class="text-center">PM Out</th>
									 </tr>
								</thead>
								<tbody id="tblbody_displayedlogs">
								</tbody>
						  </table>
						  </div>
					</div>
				</div><!--END OF CARD-->
		  </div><!--END OF FORM-GROUP-->
	 </div>
	 <div class="col-sm-5">
	 	<div class="form-group">
			<?php if(session('is_admin') == '5'): ?> 
				<?php echo $__env->make("comp.dynamic_bio", array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
			<?php else: ?>
				<?php echo $__env->make("comp.dtr_summary", array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
			<?php endif; ?>
	 </div>
	 <div class="form-group">
	 	<div class="card rounded mb-4">
	 		<div class="card-header">
	 			<select onchange="FilterMonitoring()" id="monfilt" class="form-control form-control-sm float-right onlyunithead" style="display:none; width:50%;">
	 				<option value='1'>My DTR</option>
				<option value='0'>All</option>
	 			</select>
	 			<h5 class="card-title">DTR Monitoring</h5>
	 		</div>
	 		<div class="card-body p-0" style='background-color: #F2F2F2;'>
	 		     	<div style='overflow-x:hidden; overflow-y: auto; max-height: 45vh;'>
	 			<table class="table table-hover">
	 				<thead class='table-header'>
	 					<th>Generated By</th>
	 					<th>From/To</th>
	 					<th>Status</th>
	 				</thead>
	 				<tbody id="tbl_dtrsubmitted">
	 					
	 				</tbody>
	 			</table>
	 			</div>

	 		</div>
	 	</div>
	 </div>
	 </div>
	 </div>
	 <div class="modal"  role="dialog" id="dtrsetupgeneration">
		<div class="modal-dialog" role="document">
		  <div class="modal-content">
			 <div class="modal-header">
				<h5 class="modal-title">Set DTR Date Range</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				  <span aria-hidden="true">&times;</span>
				</button>
			 </div>
			 <div class="modal-body pt-4 pb-4">
			 <div class="row">
				<div class="col-sm-6">
				  <label>From</label>
				  <input type="date" required="" autocomplete="off" id="dd_fromx" class="form-control" name="">
				</div>
				<div class="col-sm-6">
				  <label>To</label>
				  <input type="date" required="" autocomplete="off" id="dd_tox" class="form-control" name="">
				</div>
			 </div>
			 <div class="form-group mt-3" id="recent_dtr_panel" style="display: none;">
			 	<div class="mt-3">
			 		<table class="table table-bordered">

			 			<tbody id="allpasgeneration">
			 				<tr>
			 					<td colspan="2">
			 						Recent DTR
			 					</td>
			 				</tr>
			 				<tr>
			 					<td ><button title="Click to generate this DTR dates" class="btn btn-link text-primary" onclick="GenPastTimes()"  data-dismiss="modal" href=""><span id="rf"></span> <span class="text-dark">→</span> <span id="rt"></span></button></td>
			 					<td class="text-muted" style="text-align: center;" id="r_gentime">23 mins ago</td>
			 				</tr>
			 			</tbody>
			 		</table>
			 	</div>
			 </div>
			 </div>
			 <div class="modal-footer"  id="btngendtrmodal"> 
				<button type="button" class="btn btn-success rounded" onclick="RemoteGenerate()" data-dismiss="modal"><i class="fas fa-cogs"></i> Generate DTR</button>
			 </div>
		  </div>
		</div>
	 </div>
	 </div>
	 </div>	
	 </div>	
<form action="<?php echo e(route('shoot_addtimelogmanual')); ?>" method="POST">
	 <div class="modal" tabindex="-1" role="dialog" id="modal_addtimelog">
  <div class="modal-dialog" role="document">
	 <div class="modal-content">
		<div class="modal-header">
		  <h5 class="modal-title">Add Timelog</h5>
		  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			 <span aria-hidden="true">&times;</span>
		  </button>
		</div>
		<div class="modal-body">
		  <?php echo e(csrf_field()); ?>

		 <div class="form-group">
			  <label>Day</label>
			  <input type="date" required="" class="form-control" name="lgdate">
		 </div>
		 <div class="form-group">
			  <label>Time</label>
			  <input type="time" required="" class="form-control" name="lgtime">
		 </div>
		  <div class="form-group">
			  <label>Type</label>
			 <select class="form-control" required="" name="lgactype">
				  <option value="1">IN</option>
					<option value="0">OUT</option>
			 </select>
		 </div>
		</div>
		<div class="modal-footer">
		  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		  <button type="submit" class="btn btn-primary">Save</button>
		</div>
	 </div>
  </div>
</div>
</div>
</form>
<script type="text/javascript">
	
dtr_chkifuhead();


		function dtr_chkifuhead() {
		$("#unitheadname").html("Loading...");
		$.ajax({
			type:"POST",
			url: "<?php echo e(route('stole_unitheadavailability')); ?>",
			data: {_token: "<?php echo e(csrf_token()); ?>"},
			success : function(data){
				data = JSON.parse(data);
				if(data.length ==0 ){
					// NO UNIT HEAD
					$(".nouhead").show();
				}else{
					// HAS UNIT HEAD
					$(".hasuhead").show();
				}

				LoadCurrentAttendanceMonth();

			}
		})
	}




	 setInterval(function(){
	 			$(".trigger_reload").click(function(){
	 		setTimeout(function(){
	 			ResetCacheItem("dtrmonitorxdatacont");
	 			GetDTRMonitoring();
	 		},2000)
	 	})
	 },1000)
	 	function GetDTRMonitoring(){
	 		var cachename = "dtrmonitorxdatacont";
	 		// 	if(IsCacheExpired(cachename,func_processdtrmonitoring)){
			$.ajax({
	 			type: "GET",
	 			url: "<?php echo e(route('stole_dtrmonitoring')); ?>",
	 			data: {_token: "<?php echo e(csrf_token()); ?>"},
	 			success: function(data){
	 				UpdateCache(cachename,data);
		 			func_processdtrmonitoring(data);
	 			}
	 		})
	 		// 	}else{
				// 	func_processdtrmonitoring(localStorage.getItem(cachename));
	 		// 	}
	 		function func_processdtrmonitoring(data){
	
 				$("#tbl_dtrsubmitted").html(data);
 				chifuhead();
 				FilterMonitoring();
	 		}
	 	}

	 	function InstantRemoteGenerate(control_obj){
		var deid = $(control_obj).data("veid");
		var dfrom = $(control_obj).data("dfrom");
		var dto = $(control_obj).data("dto");

		GenerateTimeRecordOnModal(deid,dfrom,dto,false,true);
	}

		function chifuhead() {
			var cachename = "chuheadxmx";
			if(IsCacheExpired(cachename,funct_processcheckuhead)){
				$.ajax({
				type: "POST",
				url: "<?php echo e(route('stole_currweektasksum')); ?>",
				data: {
				_token: "<?php echo e(csrf_token()); ?>"
				},
				success: function(data) {
					UpdateCache(cachename,data);
					funct_processcheckuhead(data);
				}
				})
			}else{
				funct_processcheckuhead(localStorage.getItem(cachename));
			}
			function funct_processcheckuhead(data){
				if (data != 0) {
					$(".onlyunithead").show();
				}else{
					$(".onlyunithead").hide();
				}
				GetAllEmpNamesWithDTR();
			}
	}


	function GetAllEmpNamesWithDTR(){
		$.ajax({
			type : "GET",
			url: "<?php echo e(route('stole_getemployeenamesunderme')); ?>",
			data: {_token: "<?php echo e(csrf_token()); ?>"},
			success: function(data){
				$("#monfilt").html(data);
			}
		})
	}

	function FilterMonitoring(){
		var monfilt = $("#monfilt").val();
	$(".dtr_mine_only").hide();
	$(".dtr_employee_only").hide();
		switch(monfilt){
			case "0":
		$(".dtr_mine_only").show();
		$(".dtr_employee_only").show();
			break;
			case "1":
			$(".dtr_mine_only").show();
			break;
			default:
			// $(".dtr_employee_only").show();
			$("." + $("#monfilt").val()).show();
			break;
		}
	}


var existing_fromdate = "";
var existing_todate = "";



$("#dd_fromx").change(function(){
	 		if($("#dd_fromx").val() != null && $("#dd_tox").val() != null && $("#dd_fromx").val() != "" && $("#dd_tox").val() != ""){
	 			$("#btngendtrmodal").show();
	 		}else{
	 			$("#btngendtrmodal").hide();
	 		}
	 	});
	 	$("#dd_tox").change(function(){
	 		if($("#dd_fromx").val() != null && $("#dd_tox").val() != null && $("#dd_fromx").val() != "" && $("#dd_tox").val() != ""){
	 			$("#btngendtrmodal").show();
	 		}else{
	 			$("#btngendtrmodal").hide();
	 		}
	 	});
	 	function GenPastTimes(){
			$("#dd_fromx").val(localStorage.getItem("recent_dtrgen_from"));
			$("#dd_tox").val(localStorage.getItem("recent_dtrgen_to"));

			existing_fromdate = localStorage.getItem("recent_dtrgen_from");
			existing_todate = localStorage.getItem("recent_dtrgen_to");

			RemoteGenerate(true);
	 	}
	 	var myEID = "<?php echo e(session('user_eid')); ?>";
	 	function RemoteGenerate(iscache = false){
 			GenerateTimeRecordOnModal(myEID,$("#dd_fromx").val(),$("#dd_tox").val(),iscache);
	 	}
	 	function SetupPasGeneration(){
	 		$("#btngendtrmodal").hide();
			$("#dd_fromx").val(null);
			$("#dd_tox").val(null);
	 		if(localStorage.getItem("recent_dtrgen_from") != null){
	 			$("#recent_dtr_panel").show();
	 			$("#rf").html(localStorage.getItem("recent_formatted_dtrgen_from"));
	 			$("#rt").html(localStorage.getItem("recent_formatted_dtrgen_to"));
	 			$("#r_gentime").html(localStorage.getItem("recent_gentime"));
	 		}else{
	 			$("#recent_dtr_panel").hide();
	 		}
	 	}
function LoadCurrentAttendanceMonth(){
	$("#tblbody_displayedlogs").html(localStorage.getItem("dtremployeemonthlog"));
	ReverseAttTable();
		var starting = <?php 
		$current_date =  date('Y-m-d');
		echo json_encode($current_date);
		 ?>;
		var ending = <?php 
		$beginning_date = date("Y-m-d",strtotime("first day of this month") );
		echo json_encode($beginning_date);
		 ?>;
		var endingdate = <?php
			echo json_encode(date("F d, Y",strtotime($current_date)));
		 ?>;
		var beginningdate = <?php
			echo json_encode(date("F d, Y",strtotime($beginning_date)));
		 ?>;

		 $("#dd_from").html(beginningdate);
		$("#dd_to").html(endingdate);
		$.ajax({
			type: "get",
			url: "<?php echo e(route('load_log_records')); ?>",
			data: {_token: "<?php echo e(csrf_token()); ?>" ,date_from: beginningdate ,date_to:endingdate},
			success: function(data){
				localStorage.setItem("dtremployeemonthlog", data);
				$("#tblbody_displayedlogs").html(data);
				ReverseAttTable();
				GetDTRMonitoring();
			}
		})
	}

	function ReverseAttTable(){
		$(function(){
$("#tblbody_displayedlogs").each(function(elem,index){
var arr = $.makeArray($("tr",this).detach());
arr.reverse();
$(this).append(arr);
});
});
	}
</script>
<?php echo $__env->make('comp.dtr_dynamic', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

<?php $__env->stopSection(); ?>
<?php echo $__env->make("comp.account_manager", array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>